name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm -C apps/web lint
      - name: Build web
        run: pnpm -C apps/web build
        env:
          # Prevent Next.js telemetry and missing env errors from failing CI
          NEXT_TELEMETRY_DISABLED: '1'
      - name: Run tests
        run: |
          pnpm -C apps/web test

